### ISSUE TITLE
Improve dynamic sizing of bars and wick lines

### ISSUE THREAD

**Issue by andredumas** [andredumas/techan.js#44]
As a candlestick chart is zoomed out, clarity is lost due to the wick being css hardcoded to stroke width 1px. Would be clearer if this scales with the chart.

Styling is no longer required. It is now dynamically set by techanjs based on data displayed.
```css
path.candle.wick {
    stroke-width: 1;
}
```
